import { Book } from './books';

export const BOOKS: Book[] = [
    { id: 1, name: 'Eu, Robô', sinopse: 'Eu, Robô inicia-se com uma entrevista com a Dra. Susan Calvin, uma psicóloga roboticista da U.S Robots & Mechanical. Ela é o fio condutor da obra, responsável por contar os relatos de seu trabalho e também da evolução dos autômatos.', generos: 'Aventura, Ficção científica, Ação', autor: 'Isaac Asimov', preco: 29.90, imagem: 'https://images-na.ssl-images-amazon.com/images/I/41gCd9kNpEL.jpg'},
    { id: 2, name: 'Dune', sinopse: 'O Box Duna: primeira trilogia é formado pelos livros iniciais da saga – Duna, Messias de Duna e Filhos de Duna –, acompanhando a trajetória de Paul Atreides e sua família no planeta Arrakis.', generos: 'Aventura, Ficção científica, Ação', autor: 'Frank Hebert',preco: 142.90, imagem: 'https://images-na.ssl-images-amazon.com/images/I/41MRn6hy8-L._SX346_BO1,204,203,200_.jpg'},
    { id: 3, name: 'Enraizados', sinopse: 'Em Dvernik, assim como em todas as outras vilas da região, as pessoas vivem sob duas sombras: a da floresta que oprime e de onde saem criaturas corrompidas que trazem dor e morte; e a do dragão, um mago que de tempos em tempos visita os vilarejos para escolher uma jovem que viverá com ele por 10 anos em seu castelo.', generos: 'Ficção Científica, Romance, Fantasia, Sci-fi',  autor: 'Naomi Novik', preco: 120.00, imagem: 'https://images-na.ssl-images-amazon.com/images/I/91ti-4eLV3L.jpg'},
    { id: 4, name: 'Até que nada mais importe', sinopse: 'Em Até que nada mais importe, o respeitado pastor, autor e palestrante, Luciano Subirá nos apresenta mais que um simples livro de inspiração cristã. /nDeus não quer ser agradado pelo que fazemos, pelos nossos recordes de jejuns ou leitura bíblica. Ele espera que o busquemos com todo o nosso entendimento, que o amemos de todo o nosso coração, de toda nossa alma até que o nosso relacionamento com ele seja a mais absoluta prioridade: Até que nada mais importe!', generos: 'Cristão, Espiritualidade', autor: 'Luciano Subirá', preco: 20.00, imagem: 'https://a-static.mlcdn.com.br/618x463/ate-que-nada-mais-importe-livro-luciano-subira/shoppingospel/5779368800/7f052298dadc1ca496b492e8d477be9f.jpg'}, 
    { id: 5, name: 'Confissões', sinopse: 'A obra Confissões, de Santo Agostinho, é uma das mais consagradas, não só da filosofia cristã como do pensamento ocidental como um todo. Ao longo destes dois volumes, o bispo de Hipona narra o seu processo de conversão, partindo de sua mais tenra idade até a adolescência e a fase adulta, ressaltando como, durante grande parte de sua vida, distanciou-se dos preceitos da fé cristã que mais tarde abraçaria. De tom fortemente autobiográfico, este grande clássico apresenta ao leitor as confissões de um pecador e seu encontro com Deus.', generos: 'Cristão, Espiritualidade', autor: 'Agostinho de Hipona', preco: 20.00, imagem: 'https://images-na.ssl-images-amazon.com/images/I/518z+Qn4XYL._SX331_BO1,204,203,200_.jpg'},
    { id: 6, name: 'Cinder', sinopse: 'Cinder tem dezesseis anos e é considerada uma abominação tecnológica pela maior parte da sociedade e um fardo por sua madrasta. Por outro lado, ser ciborgue tem suas vantagens: a interface de seu cérebro lhe deu a capacidade sobre-humana de consertar tudo — robôs, aerodeslizadores, os próprios membros cibernéticos quebrados—, tornando-a a melhor mecânica de Nova Pequim. Sua reputação faz com que o herdeiro do império, o príncipe Kai em pessoa, apareça em seu estande na feira, solicitando o conserto de um androide antes do baile anual.', generos: 'Sci-fi, Fantasia, Romance', autor: 'Marissa Meyer', preco: 24.00, imagem: 'https://m.media-amazon.com/images/I/41ARP7x6AGL.jpg'},
    { id: 7, name: 'Drácula', sinopse: 'Um romance de terror gótico lançado em 1897, escrito pelo autor irlandês Bram Stoker, tendo como protagonista o vampiro Conde Drácula. Tornou-se a mais famosa história de vampiro da literatura.', generos: 'Sci-fi, Fantasia, Romance', autor: 'Bram Stoker', preco: 24.00, imagem: 'https://m.media-amazon.com/images/I/51d3KGto3+L.jpg'},
    { id: 8, name: 'Memórias Póstumas de Brás Cubas', sinopse: 'Pertencente a uma família abastada do século XIX, Brás Cubas narra primeiramente sua morte e enterro onde apareceram onze amigos. Por conseguinte, ele relata diversos momentos de sua vida, desde eventos da sua infância, adolescência e fase adulta.', generos: 'Romance', autor: 'Bram Stoker', preco: 15.00, imagem: 'https://m.media-amazon.com/images/I/51FwHerjYKL.jpg'},
    { id: 9, name: 'Orgulho e Preconceito', sinopse: 'A história mostra a maneira com que a personagem Elizabeth Bennet lida com os problemas relacionados à educação, cultura, moral e casamento na sociedade aristocrática do início do século XIX, na Inglaterra. Elizabeth é a segunda de 5 filhas de um proprietário rural na cidade fictícia de Meryton, em Hertfordshire, não muito longe de Londres.', generos: 'Romance', autor: 'Jane Austen', preco: 40.00, imagem: 'https://images-na.ssl-images-amazon.com/images/I/719esIW3D7L.jpg'}
]